# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llm_service.proto\x12\x03llm\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\" \n\x0cTextResponse\x12\x10\n\x08response\x18\x01 \x01(\t2B\n\nLLMService\x12\x34\n\x0bProcessText\x12\x10.llm.TextRequest\x1a\x11.llm.TextResponse\"\x00\x42\x16Z\x14go_llm_service/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\024go_llm_service/proto'
  _globals['_TEXTREQUEST']._serialized_start=26
  _globals['_TEXTREQUEST']._serialized_end=53
  _globals['_TEXTRESPONSE']._serialized_start=55
  _globals['_TEXTRESPONSE']._serialized_end=87
  _globals['_LLMSERVICE']._serialized_start=89
  _globals['_LLMSERVICE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
